# Generated by Django 5.2.6 on 2025-10-07 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='country',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='historicalcountry',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='historicaltown',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='town',
            name='agency_id',
        ),
        migrations.AlterField(
            model_name='agency',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Seuls les caractères de A-Z, 0-9 et _ sont autorisés pour le code')]),
        ),
        migrations.AlterField(
            model_name='historicalagency',
            name='code',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]+$', 'Seuls les caractères de A-Z, 0-9 et _ sont autorisés pour le code')]),
        ),
        migrations.AddConstraint(
            model_name='agency',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_agency_name_per_country'),
        ),
    ]
