# Generated by Django 5.2.6 on 2025-12-21 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='country.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Devise'),
        ),
    ]
