# Generated by Django 5.2.6 on 2025-10-07 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_agency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', "Seuls les caractères A-Z, 0-9 et _ sont autorisés pour le code d'agence.")]),
        ),
        migrations.AlterField(
            model_name='historicalagency',
            name='code',
            field=models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', "Seuls les caractères A-Z, 0-9 et _ sont autorisés pour le code d'agence.")]),
        ),
    ]
