# Generated by Django 5.2.6 on 2025-10-10 14:06

import apps.country.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_agency_code_alter_historicalagency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=apps.country.models.media_directory_path),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='logo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
