# Generated by Django 5.2.6 on 2025-10-10 15:06

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_agency_logo_historicalagency_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='agency',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Télephone'),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Télephone'),
        ),
    ]
