# Generated by Django 5.2.6 on 2025-10-12 15:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_agency_address_agency_phone_historicalagency_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region='FR', verbose_name='Télephone'),
        ),
        migrations.AlterField(
            model_name='historicalagency',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='historicalagency',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region='FR', verbose_name='Télephone'),
        ),
    ]
