# Generated by Django 5.2.6 on 2025-12-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('transferts', '0004_remove_simcard_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='simcards',
            field=models.ManyToManyField(blank=True, related_name='users_per_simcard', to='transferts.simcard'),
        ),
    ]
