# Generated by Django 5.2.6 on 2025-12-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_simcards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='simcards',
        ),
    ]
