# Generated by Django 5.2.6 on 2025-11-27 08:43

import apps.core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=255, verbose_name='Dénomination')),
                ('Address', models.CharField(max_length=255, verbose_name='Addresse')),
                ('Phone', models.CharField(max_length=20, verbose_name='N° Tél:')),
                ('Head_office', models.CharField(max_length=255, verbose_name='Siège social')),
                ('logo', models.FileField(blank=True, null=True, upload_to=apps.core.models.media_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
