# Generated by Django 5.2.6 on 2025-11-18 05:28

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import phonenumber_field.modelfields
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPhoneOperator',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.country', verbose_name='Pays')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Operateur Télephonique',
                'verbose_name_plural': 'historical Operateur Télephoniques',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PhoneOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Operateur Télephonique',
            },
        ),
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Numéro')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Solde du compte')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='transferts.phoneoperator', verbose_name='Opérateur téléphonique')),
            ],
            options={
                'verbose_name': 'Carte SIM',
                'verbose_name_plural': 'Cartes SIM',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransfert',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('operation_type', models.CharField(blank=True, choices=[('S', 'Retrait Client (Sortie de fond)'), ('E', 'Dépôt Client (Entrée de fond)')], max_length=2, null=True)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant Opération')),
                ('screenshot', models.TextField(blank=True, max_length=100, null=True, verbose_name="Capture d'écran")),
                ('commission_amount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('commission_amount', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant Commission')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.agency', verbose_name='Agence')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sim_card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transferts.simcard', verbose_name='SIM')),
            ],
            options={
                'verbose_name': 'historical Transfert',
                'verbose_name_plural': 'historical Transferts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(blank=True, choices=[('S', 'Retrait Client (Sortie de fond)'), ('E', 'Dépôt Client (Entrée de fond)')], max_length=2, null=True)),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant Opération')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=apps.core.models.media_directory_path, verbose_name="Capture d'écran")),
                ('commission_amount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('commission_amount', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant Commission')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.agency', verbose_name='Agence')),
                ('sim_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferts.simcard', verbose_name='SIM')),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant Opération')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.agency', verbose_name='Agence')),
                ('transfer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='transferts.transfert', verbose_name='Transfert')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='phoneoperator',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_country_operator_name'),
        ),
        migrations.AddConstraint(
            model_name='simcard',
            constraint=models.UniqueConstraint(fields=('operator', 'number'), name='unique_operator_simcard_num'),
        ),
    ]
