# Generated by Django 5.2.6 on 2025-11-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='sim_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfert_sim_card', to='transferts.simcard', verbose_name='SIM'),
        ),
    ]
