# Generated by Django 5.2.6 on 2025-11-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simcard',
            name='balance_currency',
        ),
        migrations.AlterField(
            model_name='simcard',
            name='balance',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Solde du compte'),
        ),
    ]
