# Generated by Django 5.2.6 on 2025-11-20 10:15

import djmoney.models.fields
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0002_alter_transfert_sim_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransfert',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Solde du compte'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Numéro'),
        ),
    ]
