# Generated by Django 5.2.6 on 2025-12-13 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0002_remove_simcard_balance_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simcard',
            name='users',
            field=models.ManyToManyField(related_name='simcards', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs'),
        ),
    ]
