# Generated by Django 5.2.6 on 2025-11-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0003_alter_historicaltransfert_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransfert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='description',
        ),
    ]
