# Generated by Django 5.2.6 on 2025-12-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0003_simcard_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simcard',
            name='users',
        ),
    ]
