# Generated by Django 5.2.6 on 2025-11-24 05:39

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0004_remove_historicaltransfert_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, verbose_name='Montant Opération'),
        ),
        migrations.AlterField(
            model_name='historicaltransfert',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, verbose_name='Montant Opération'),
        ),
        migrations.AlterField(
            model_name='historicaltransfert',
            name='commission_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, verbose_name='Montant Commission'),
        ),
        migrations.AlterField(
            model_name='historicaltransfert',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('S', 'Retrait Client '), ('E', 'Dépôt Client ')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, verbose_name='Montant Opération'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='commission_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=12, verbose_name='Montant Commission'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('S', 'Retrait Client '), ('E', 'Dépôt Client ')], max_length=2, null=True),
        ),
    ]
