# Generated by Django 5.2.6 on 2025-11-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0005_alter_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcard',
            name='currency',
            field=models.CharField(default=2, max_length=10, verbose_name='Devise'),
            preserve_default=False,
        ),
    ]
