# Generated by Django 5.2.6 on 2025-12-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0005_simcard_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransfert',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='historicaltransfert',
            name='commission_amount_currency',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='commission_amount_currency',
        ),
        migrations.AlterField(
            model_name='historicaltransfert',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant Opération'),
        ),
        migrations.AlterField(
            model_name='historicaltransfert',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant Commission'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant Opération'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant Commission'),
        ),
    ]
