# Generated by Django 5.2.6 on 2025-12-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0006_remove_historicaltransfert_amount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransfert',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Solde du compte'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Solde du compte'),
        ),
    ]
