# Generated by Django 5.2.6 on 2025-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0006_simcard_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='historicaltransfert',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='transfert',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
    ]
