# Generated by Django 5.2.6 on 2025-12-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferts', '0007_historicaltransfert_balance_transfert_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransfert',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant Opération'),
        ),
        migrations.AlterField(
            model_name='historicaltransfert',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant Commission'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant Opération'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant Commission'),
        ),
    ]
