# Generated by Django 5.2.6 on 2025-12-21 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('country', '0002_alter_agency_country_alter_country_currency'),
        ('transferts', '0008_alter_historicaltransfert_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.agency', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='transfer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='transferts.transfert', verbose_name='Transfert'),
        ),
        migrations.AlterField(
            model_name='phoneoperator',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='transferts.phoneoperator', verbose_name='Opérateur téléphonique'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.agency', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='transfert',
            name='sim_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfert_sim_card', to='transferts.simcard', verbose_name='SIM'),
        ),
    ]
