# Generated by Django 5.2.6 on 2025-11-18 05:28

import datetime
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('PD', 'Produits'), ('CH', 'Charges')], max_length=5, verbose_name='Type opération')),
                ('date_operation', models.DateField(default=datetime.date.today, verbose_name='Date opération')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
