# Generated by Django 5.2.6 on 2025-11-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
        ('country', '0001_initial'),
        ('transferts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.agency', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='commission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entry', to='transferts.commission'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency', verbose_name='Devise'),
        ),
    ]
