# Generated by Django 5.2.6 on 2025-11-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounting',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='accounting',
            old_name='Amount_currency',
            new_name='amount_currency',
        ),
    ]
