# Generated by Django 5.2.6 on 2025-11-18 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('transferts', '0002_alter_transfert_sim_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='commission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entry', to='transferts.commission'),
        ),
    ]
