# Generated by Django 5.2.6 on 2025-11-29 12:03

import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='accounting',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=djmoney.money.Money(0, 'XOF'), max_digits=12, verbose_name='Montant'),
        ),
    ]
