# Generated by Django 5.2.6 on 2025-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_accounting_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
    ]
