# Generated by Django 5.2.6 on 2025-12-21 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_accounting_amount_currency_and_more'),
        ('core', '0001_initial'),
        ('country', '0001_initial'),
        ('transferts', '0008_alter_historicaltransfert_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.agency', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='commission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounting_entry', to='transferts.commission'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Devise'),
        ),
    ]
