# Generated by Django 5.2.6 on 2025-12-23 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_accounting_agency_alter_accounting_commission_and_more'),
        ('transferts', '0009_alter_commission_agency_alter_commission_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='commission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entry', to='transferts.commission'),
        ),
    ]
