# Generated by Django 5.2.6 on 2025-10-14 17:35

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import phonenumber_field.modelfields
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0007_alter_agency_address_alter_agency_phone_and_more'),
        ('customer', '0005_alter_customer_idcardnumber_alter_customer_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPackage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('package_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=500, verbose_name='Description du colis')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Prix')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte bancaire'), ('Mobile Money', 'Mobile Money')], max_length=50, verbose_name='Mode de paiement')),
                ('mobile_money_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region='FR', verbose_name='Numéro Mobile Money')),
                ('status', models.CharField(choices=[('PAYE', 'Payé'), ('NON_PAYE', 'Non payé')], max_length=15, verbose_name='Statut')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.agency', verbose_name='Agence')),
                ('arrival_town', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.town', verbose_name="Ville d'arrivé")),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.customer', verbose_name='Nom client')),
                ('departure_town', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.town', verbose_name='Ville de départ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Colis',
                'verbose_name_plural': 'historical Colis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=500, verbose_name='Description du colis')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Prix')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte bancaire'), ('Mobile Money', 'Mobile Money')], max_length=50, verbose_name='Mode de paiement')),
                ('mobile_money_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region='FR', verbose_name='Numéro Mobile Money')),
                ('status', models.CharField(choices=[('PAYE', 'Payé'), ('NON_PAYE', 'Non payé')], max_length=15, verbose_name='Statut')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.agency', verbose_name='Agence')),
                ('arrival_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_town', to='country.town', verbose_name="Ville d'arrivé")),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Nom client')),
                ('departure_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_town', to='country.town', verbose_name='Ville de départ')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
            },
        ),
    ]
