# Generated by Django 5.2.6 on 2025-10-15 17:29

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackage',
            name='package_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de colis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpackage',
            name='receiver_name',
            field=models.CharField(default='receiver', max_length=120, verbose_name='Nom-Prénoms receveur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpackage',
            name='receiver_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region='FR', verbose_name='Tél receveur'),
        ),
        migrations.AddField(
            model_name='package',
            name='package_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de colis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_name',
            field=models.CharField(default='receiver', max_length=120, verbose_name='Nom-Prénoms receveur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='receiver_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region='FR', verbose_name='Tél receveur'),
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description du colis'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description du colis'),
        ),
    ]
