# Generated by Django 5.2.6 on 2025-11-20 10:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpackage',
            name='receiver_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None, verbose_name='Tél receveur'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiver_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None, verbose_name='Tél receveur'),
        ),
    ]
