# Generated by Django 5.2.6 on 2025-11-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpackage',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='historicalpackage',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix'),
        ),
    ]
