# Generated by Django 5.2.6 on 2025-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_historicalpackage_receiver_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpackage',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
    ]
