# Generated by Django 5.2.6 on 2025-12-21 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('country', '0002_alter_agency_country_alter_country_currency'),
        ('customer', '0002_alter_customer_agency_alter_customer_country'),
        ('package', '0002_remove_historicalpackage_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.agency', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='package',
            name='arrival_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrival_town', to='country.town', verbose_name="Ville d'arrivé"),
        ),
        migrations.AlterField(
            model_name='package',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='package',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='Nom client'),
        ),
        migrations.AlterField(
            model_name='package',
            name='departure_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_town', to='country.town', verbose_name='Ville de départ'),
        ),
    ]
