# Generated by Django 5.2.6 on 2025-11-18 05:28

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCustomer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('firstName', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('lastName', models.CharField(max_length=150, verbose_name='Nom')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, default='', max_length=128, region='FR', verbose_name='Télephone')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('IDCardNumber', models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, verbose_name="N° pièce d'identificaiton")),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Adresse')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.agency', verbose_name='Agence')),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.country', verbose_name='Pays')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Client',
                'verbose_name_plural': 'historical  Clients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('firstName', models.CharField(max_length=150, verbose_name='Prénoms')),
                ('lastName', models.CharField(max_length=150, verbose_name='Nom')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='FR', unique=True, verbose_name='Télephone')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('IDCardNumber', models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name="N° pièce d'identificaiton")),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Adresse')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.agency', verbose_name='Agence')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country', verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': ' Clients',
                'unique_together': {('firstName', 'lastName', 'phone_number')},
            },
        ),
    ]
