# Generated by Django 5.2.6 on 2025-12-21 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_agency_country_alter_country_currency'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.agency', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country.country', verbose_name='Pays'),
        ),
    ]
