# Generated by Django 5.2.6 on 2025-11-20 10:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, unique=True, verbose_name='Télephone'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None, verbose_name='Télephone'),
        ),
    ]
