# Generated by Django 5.2.6 on 2025-10-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_code_alter_historicalcustomer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
