# Generated by Django 5.2.6 on 2025-10-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_agency_code_alter_historicalagency_code'),
        ('customer', '0003_alter_customer_code_alter_historicalcustomer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.agency', verbose_name='Agence'),
        ),
    ]
