# Generated by Django 5.2.6 on 2025-10-12 15:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='IDCardNumber',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name="N° pièce d'identificaiton"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='FR', unique=True, verbose_name='Télephone'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='IDCardNumber',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, null=True, verbose_name="N° pièce d'identificaiton"),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default='', max_length=128, region='FR', verbose_name='Télephone'),
        ),
    ]
