# Generated by Django 5.2.6 on 2025-11-27 08:43

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import phonenumber_field.modelfields
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('country', '0001_initial'),
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('ticket_code', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_date', models.DateField(verbose_name='Date de départ')),
                ('departure_hour', models.TimeField(verbose_name='Heure de départ')),
                ('ticket_price_currency', djmoney.models.fields.CurrencyField(choices=[(1, 'Franc CFA BCEAO'), (2, 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('ticket_price', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant du billet')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte bancaire'), ('Mobile Money', 'Mobile Money')], max_length=50, verbose_name='Mode de paiement')),
                ('mobile_money_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None, verbose_name='Numéro Mobile Money')),
                ('status', models.CharField(choices=[('PAYE', 'Payé'), ('NON_PAYE', 'Non payé')], max_length=15, verbose_name='Statut')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.agency', verbose_name='Agence')),
                ('arrival_town', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.town', verbose_name="Ville d'arrivé")),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.currency', verbose_name='Devise')),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer.customer', verbose_name='Nom client')),
                ('departure_town', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.town', verbose_name='Ville de départ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ticket',
                'verbose_name_plural': 'historical Tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_code', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_date', models.DateField(verbose_name='Date de départ')),
                ('departure_hour', models.TimeField(verbose_name='Heure de départ')),
                ('ticket_price_currency', djmoney.models.fields.CurrencyField(choices=[(1, 'Franc CFA BCEAO'), (2, 'Franc Guinéen')], default='XOF', editable=False, max_length=3)),
                ('ticket_price', djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Montant du billet')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte bancaire'), ('Mobile Money', 'Mobile Money')], max_length=50, verbose_name='Mode de paiement')),
                ('mobile_money_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None, verbose_name='Numéro Mobile Money')),
                ('status', models.CharField(choices=[('PAYE', 'Payé'), ('NON_PAYE', 'Non payé')], max_length=15, verbose_name='Statut')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.agency', verbose_name='Agence')),
                ('arrival_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivées', to='country.town', verbose_name="Ville d'arrivé")),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency', verbose_name='Devise')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Nom client')),
                ('departure_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to='country.town', verbose_name='Ville de départ')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
