# Generated by Django 5.2.6 on 2025-11-20 10:15

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='mobile_money_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None, verbose_name='Numéro Mobile Money'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mobile_money_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None, verbose_name='Numéro Mobile Money'),
        ),
    ]
