# Generated by Django 5.2.6 on 2025-10-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalticket',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ticket', 'verbose_name_plural': 'historical Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
