# Generated by Django 5.2.6 on 2025-11-29 12:38

import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='ticket_price_currency',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_price_currency',
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='ticket_price',
            field=models.DecimalField(decimal_places=0, default=djmoney.money.Money(0, 'XOF'), max_digits=12, verbose_name='Montant du billet'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price',
            field=models.DecimalField(decimal_places=0, default=djmoney.money.Money(0, 'XOF'), max_digits=12, verbose_name='Montant du billet'),
        ),
    ]
