# Generated by Django 5.2.6 on 2025-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_alter_historicalticket_mobile_money_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
    ]
