# Generated by Django 5.2.6 on 2025-10-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_alter_historicalticket_options_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='ticket_price_currency',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_price_currency',
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='ticket_price',
            field=models.PositiveIntegerField(verbose_name='Montant du billet'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price',
            field=models.PositiveIntegerField(verbose_name='Montant du billet'),
        ),
    ]
