# Generated by Django 5.2.6 on 2025-10-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_agency_code_alter_historicalagency_code'),
        ('passengers', '0003_remove_historicalticket_ticket_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='agency',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.agency', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='country.agency', verbose_name='Agence'),
            preserve_default=False,
        ),
    ]
