# Generated by Django 5.2.6 on 2025-10-09 16:33

import djmoney.models.fields
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0005_historicalticket_ticket_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='mobile_money_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Numéro Mobile Money'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='ticket_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mobile_money_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='FR', verbose_name='Numéro Mobile Money'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dollar Américain'), ('EUR', 'Euro'), ('XOF', 'Franc CFA BCEAO'), ('GNF', 'Franc Guinéen')], default='XOF', editable=False, max_length=3),
        ),
    ]
