# Generated by Django 5.2.6 on 2025-10-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_agency_code_alter_historicalagency_code'),
        ('customer', '0003_alter_customer_code_alter_historicalcustomer_code'),
        ('passengers', '0006_alter_historicalticket_mobile_money_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.agency', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrival_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivées', to='country.town', verbose_name="Ville d'arrivé"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Nom client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departs', to='country.town', verbose_name='Ville de départ'),
        ),
    ]
