# Generated by Django 5.2.6 on 2025-10-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0007_alter_ticket_agency_alter_ticket_arrival_town_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='status',
            field=models.BooleanField(choices=[('1', 'Payé'), ('0', 'Non payé')], default=1, verbose_name='Statut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(choices=[('1', 'Payé'), ('0', 'Non payé')], default=1, verbose_name='Statut'),
            preserve_default=False,
        ),
    ]
