# Generated by Django 5.2.6 on 2025-10-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0008_historicalticket_status_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.CharField(choices=[('PAYE', 'Payé'), ('NON PAYE', 'Non payé')], max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PAYE', 'Payé'), ('NON PAYE', 'Non payé')], max_length=15, verbose_name='Statut'),
        ),
    ]
