# Generated by Django 5.2.6 on 2025-10-12 15:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0009_alter_historicalticket_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='mobile_money_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region='FR', verbose_name='Numéro Mobile Money'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte bancaire'), ('Mobile Money', 'Mobile Money')], max_length=50, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='mobile_money_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region='FR', verbose_name='Numéro Mobile Money'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte bancaire'), ('Mobile Money', 'Mobile Money')], max_length=50, verbose_name='Mode de paiement'),
        ),
    ]
