# Generated by Django 5.2.6 on 2025-10-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0010_alter_historicalticket_mobile_money_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.CharField(choices=[('PAYE', 'Payé'), ('NON_PAYE', 'Non payé')], max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PAYE', 'Payé'), ('NON_PAYE', 'Non payé')], max_length=15, verbose_name='Statut'),
        ),
    ]
