# Generated by Django 5.2.6 on 2025-10-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_historicalmessage_historicalroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmessage',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_media_directory_path'),
        ),
    ]
